language: node_js
node_js: '10.15.1'
cache:
directories:
  - node_modules
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database test_chat_db;' -U postgres
script:
  - npm run test
after_script:
  - npm run coveralls
